Adding AddVolunteer page and AddVolunteerForm
taller-de-desarrollo-proyectos-III/front-end pull request #9
Opened 2020-10-28 14:42 UTC by lautarodelosheros

Abro el merge request para ir viendo si voy por buen camino.

En un principio usé el "HoC" de formik porque me parecía más prolijo pero como no podía usar el hook de create volunteer pasé al componente común. Igualmente no logré usar el hook :S

Está funcionando con el componente llamando en el callback de submit a BackendService.createVolunteer

El formulario se ve horrible, no le puse ningún estilo.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/14253506/97450872-ee6a1480-1911-11eb-829a-6a8d980717b4.png">

2020-10-28 16:06 UTC, BlancoSebastianEzequiel commented on package.json
> +    "@types/yup": "^0.29.8",
sacaria el `^` y y actualizaria el lock de nuevo

2020-10-28 16:07 UTC, BlancoSebastianEzequiel commented on src/components/AddVolunteerForm/index.tsx
> +export const AddVolunteerForm: FunctionComponent = () => {
lo llamaria `CreateVolunteer`

2020-10-28 16:07 UTC, BlancoSebastianEzequiel commented on src/components/AddVolunteerForm/useAddVolunteerFormManagement.ts
> +}
Esto deberia ir en el container y pasarle por prop lo necesario al component

2020-10-28 16:14 UTC, BlancoSebastianEzequiel commented on src/hooks/Volunteers/useCreateVolunteer.ts
> +};
Aca no es necesario el `useEffect` ya que esta request http se va a ejecutar en el handler del `onSubmit`. Por lo tanto podriamos hacer algo asi
```typescript
export const useCreateVolunteer = () => {
    const createVolunteer = ({ name, surname, dni }: IUseCreateVolunteerVariables) =>  
         BackendService.createVolunteer({ name, surname, dni })
    return { createVolunteer };
}
```

2020-10-28 16:15 UTC, BlancoSebastianEzequiel commented on src/pages/AddVolunteer/component.tsx
> +export const AddVolunteer: FunctionComponent = () => (
Lo llamaria `CreateVolunteerate`

2020-10-28 16:22 UTC, BlancoSebastianEzequiel commented on src/pages/AddVolunteer/container.tsx
> +};
Aca habria que agregar la logica del hook y declaar el onSumit. algo asi:
```typescript
export const AddVolunteerContainer: FunctionComponent = () => {
  const { createVolunteer } = useCreateVolunteers();
  
  const onSubmit = async (addVolunteerFormFields: IAddVolunteerFormFields) => {
     await createVolunteer(addVolunteerFormFields);
     history.push(/<home>);  // esto lo vemo bien dsp
  }
  return  <AddVolunteer />
};
```

2020-10-28 16:24 UTC, BlancoSebastianEzequiel commented on src/routes.tsx
> +      <Route exact path={"/addVolunteer"}>
hara que sea: ` <Route exact path={"/volunteers/create"}>`

2020-10-28 16:24 UTC, BlancoSebastianEzequiel commented on src/services/Backend/Service.ts
> +
Borraria este espacio demas

2020-10-28 16:27 UTC, BlancoSebastianEzequiel requested changes
Con respecto al css, diria que hace falta colocar los inputs dentro de una card, que tenga ciero radio, u shaddow y centrarla en la pantalla, ponerle padding, etc

y dsp faltaria darle una sepacion con margin entre los inputs, darles radio, etc.

2020-10-30 22:03 UTC, lautarodelosheros commented
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/14253506/97760734-9df5e100-1ae2-11eb-9f86-e6d5f089026a.png">

2020-10-31 00:26 UTC, BlancoSebastianEzequiel commented on src/hooks/Volunteers/useCreateVolunteer.ts
> +  return { createVolunteer };
No es necesario el `then` aca porque se hace un await en el onSubmit cuando se llama a la funcion. en este caso el hook devuelve esta funcion y la llamamos haciendo un await, asique devolveria la promesa de una asi:
```typescript
const createVolunteer = ({ name, surname, dni }: IUseCreateVolunteerVariables) =>
   BackendService.createVolunteer({ name, surname, dni })
```

2020-10-31 00:26 UTC, BlancoSebastianEzequiel commented on src/pages/CreateVolunteer/component.tsx
> +} from "../../components/CreateVolunteerForm";
U[saria el alias como: `from "$components/CreateVolunteerForm";`

2020-10-31 00:27 UTC, BlancoSebastianEzequiel commented on src/pages/CreateVolunteer/component.tsx
> +import { MainContent } from "../../components/MainContent";
Usaría el alias: `import { MainContent } from "$components/MainContent";`

2020-10-31 00:27 UTC, BlancoSebastianEzequiel commented on src/services/Backend/Service.ts
> +import { IUseCreateVolunteerVariables } from "../../hooks/Volunteers/useCreateVolunteer";
Aca tmb el alias: `import { IUseCreateVolunteerVariables } from "$hooks";`

2020-10-31 00:32 UTC, BlancoSebastianEzequiel commented on src/components/CreateVolunteerForm/index.tsx
> +    <Formik
Agregaria un titulo nada mas asi: 

```typescript
<Card>
   <h1 className={styles.title}>Create Voluntario</h1>
   <Formik
   .....etc
```
y metele algun font-size, font-weight, y demas, algo asi:

```scss
.title {
   color: $mainBlue;
   font-size: $fontSize-xxl;
   font-weight: bold;
   margin: 0;
}
```
Ahi use las constantes nuestras

2020-10-31 00:32 UTC, BlancoSebastianEzequiel approved these changes

2020-10-31 00:33 UTC, BlancoSebastianEzequiel commented on src/components/CreateVolunteerForm/index.tsx
> +    <Formik
O quizas ahora que lo pienso, el titulo podria ir fuera de la card, asi queda mejor

2020-10-31 00:34 UTC, BlancoSebastianEzequiel commented on src/components/CreateVolunteerForm/index.tsx
> +    <Formik
Y meteria un margin-top asi no esta pegado al NavBar

2020-10-31 04:27 UTC, lautarodelosheros commented
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/14253506/97771074-378bb580-1b18-11eb-8059-87dceb59299b.png">

2020-10-31 04:31 UTC, BlancoSebastianEzequiel approved these changes
Quedo muy bueno! Me di cuenta que faltaria un selector para elegir la comission, pero lo haria en otro pr, asi este lo cerramos

2020-10-31 22:06 UTC, merged